# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b4e42d4546b0f98302fa05ccf30b32a47b2eb78976617c932f1b515630eb8060f365a3245eff974666401fc51cdce383398ba80d4c1b041cce21854f473d87

test:
  secret_key_base: 18a6f6ae632fcd338e2efd68a9f968947a67ffa6d30abe3201fb9090925a08e8dac47d866087a9351f23513f0aaf773c614dd2d27a3f1c8308b33425259800d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
